### ISSUE TITLE
Support react / JSXText selector?

### ISSUE THREAD

**Issue by mnahkies** [seleb/eslint-plugin-no-smart-quotes#5]
As far as I can tell the rule fails to find smart quotes that are embedded in JSX expressions. 

From poking around at the code it seems like it would have to also match `JSXText` in addition to `Literal` here: https://github.com/seleb/eslint-plugin-no-smart-quotes/blob/master/lib/rules/no-smart-quotes.js#L47

Additionally I think it would need to handle auto-fixing differently (the detection part appeared to work fine)

Example component:
```
import React from 'react';

export const component = () => {
  const found = "We found this '’' one though "
  return (
    <div>
      <h1>We couldn’t find this smart quote</h1>
    </div>
  );
};
```

**Comment by seleb** [comment]
added support for this in v1.2.0; thanks for the feedback!

**Comment by mnahkies** [comment]
@seleb thanks for the prompt response! I tested it this morning in the project that I was originally having issues with this, and found that the autofix was not working correctly. After a bit of messing around I was able to solve this and have opened a PR here https://github.com/seleb/eslint-plugin-no-smart-quotes/pull/6
